name: notification_case
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Notification
  awesome_notifications: ^0.9.2
  flutter_local_notifications: ^16.3.2

  # Dependency Injection
  get_it: ^7.6.7

  # State Management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
